In [1]:
import pandas as pd
datasets_of_interest = ['FICO', 'CKD', 'HEART_DISEASE', 'BREAST_CANCER', 'MIMIC', 'ADULT', 'PHARYNGITIS']
imputations_of_interest = ['Mean', 'MICE', 'MissForest', 'MIWAE']

load_statuses_baselines = {
    'dataset': [],
    'imputation': [],
    'slurm_iter': [],
    'success': []
}
for dataset_of_interest in datasets_of_interest:
    for ds_name in [f'{dataset_of_interest}', f'{dataset_of_interest}_0.25', f'{dataset_of_interest}_0.5', f'{dataset_of_interest}_0.75']:
        for imputation_method in imputations_of_interest:
            for s_iter in range(120):
                load_statuses_baselines['slurm_iter'] = load_statuses_baselines['slurm_iter'] + [s_iter]
                load_statuses_baselines['imputation'] = load_statuses_baselines['imputation'] + [imputation_method]
                load_statuses_baselines['dataset'] = load_statuses_baselines['dataset'] + [ds_name]
                
                #df = pd.read_csv(f'./parallelized_results/baselines_2024-02_01_iter_{s_iter}_10_imp_all.csv')
                try:
                    df = pd.read_csv(f'./parallelized_results/baselines_iter_{s_iter}_{ds_name}_{imputation_method}.csv')
                    load_statuses_baselines['success'] = load_statuses_baselines['success'] + [1]
                except:
                    load_statuses_baselines['success'] = load_statuses_baselines['success'] + [0]

In [11]:
load_statuses_baselines = pd.DataFrame(load_statuses_baselines)
load_statuses_baselines['success'].mean()

0.43467261904761906

In [13]:
load_statuses_baselines[load_statuses_baselines['dataset'] == 'FICO']

0.8729166666666667

In [26]:

load_statuses_imps = {
    'dataset': [],
    'imputation': [],
    'success': []
}
for dataset_of_interest in datasets_of_interest:
    for ds_name in [dataset_of_interest]:
        for imputation_method in imputations_of_interest:
            for subsample in ['', '_0.25', '_0.5', '_0.75']:
                load_statuses_imps['imputation'] = load_statuses_imps['imputation'] + [imputation_method]
                load_statuses_imps['dataset'] = load_statuses_imps['dataset'] + [ds_name + subsample]

                try:
                    df = pd.read_csv(f'../../handling_missing_data/timing_stats_{ds_name}{subsample}_{imputation_method}_5_3.csv')
                    df = df.drop_duplicates(['imputation', 'dataset', 'holdout_set', 'validation_set', 'm'])
                    df = df[(df['dataset'] == ds_name + subsample) & (df['imputation'] == imputation_method)]
                    load_statuses_imps['success'] = load_statuses_imps['success'] + [df.shape[0] / 500]
                except:
                    load_statuses_imps['success'] = load_statuses_imps['success'] + [0]

In [27]:
load_statuses_imps = pd.DataFrame(load_statuses_imps)
load_statuses_imps['success'].mean()

0.7322321428571429

In [29]:
#(load_statuses_imps['success'] > 0) & 
load_statuses_imps[(load_statuses_imps['success'] < 1)].sort_values('success')

               dataset  imputation  success
9            FICO_0.25  MissForest    0.000
93          ADULT_0.25       MIWAE    0.000
91          ADULT_0.75  MissForest    0.000
90           ADULT_0.5  MissForest    0.000
89          ADULT_0.25  MissForest    0.000
88               ADULT  MissForest    0.000
78           MIMIC_0.5       MIWAE    0.000
75          MIMIC_0.75  MissForest    0.000
74           MIMIC_0.5  MissForest    0.000
94           ADULT_0.5       MIWAE    0.000
71          MIMIC_0.75        MICE    0.000
70           MIMIC_0.5        MICE    0.000
67          MIMIC_0.75        Mean    0.000
95          ADULT_0.75       MIWAE    0.000
10            FICO_0.5  MissForest    0.000
11           FICO_0.75  MissForest    0.000
45  HEART_DISEASE_0.25       MIWAE    0.000
66           MIMIC_0.5        Mean    0.000
40       HEART_DISEASE  MissForest    0.006
43  HEART_DISEASE_0.75  MissForest    0.012
42   HEART_DISEASE_0.5  MissForest    0.012
84               ADULT        MICE    0.034
41  HEART_DISEASE_0.25  MissForest    0.044
87          ADULT_0.75        MICE    0.046
76               MIMIC       MIWAE    0.062
86           ADULT_0.5        MICE    0.070
72               MIMIC  MissForest    0.104
85          ADULT_0.25        MICE    0.130
92               ADULT       MIWAE    0.248
73          MIMIC_0.25  MissForest    0.354
79          MIMIC_0.75       MIWAE    0.724
27            CKD_0.75  MissForest    0.740
54   BREAST_CANCER_0.5        MICE    0.752
53  BREAST_CANCER_0.25        MICE    0.774
77          MIMIC_0.25       MIWAE    0.940
55  BREAST_CANCER_0.75        MICE    0.978
52       BREAST_CANCER        MICE    0.980

In [8]:
#(load_statuses_imps['success'] > 0) & 
load_statuses_imps[(load_statuses_imps['success'] == 1)].sort_values('dataset')

              dataset  imputation  success
80              ADULT        Mean      1.0
81         ADULT_0.25        Mean      1.0
82          ADULT_0.5        Mean      1.0
83         ADULT_0.75        Mean      1.0
48      BREAST_CANCER        Mean      1.0
..                ...         ...      ...
110   PHARYNGITIS_0.5       MIWAE      1.0
99   PHARYNGITIS_0.75        Mean      1.0
103  PHARYNGITIS_0.75        MICE      1.0
107  PHARYNGITIS_0.75  MissForest      1.0
111  PHARYNGITIS_0.75       MIWAE      1.0

[75 rows x 3 columns]

In [10]:
load_statuses_imps[load_statuses_imps['dataset'].isin([f'PHARYNGITIS{i}' for i in ['', '_0.25', '_0.75', '_0.5']])]

              dataset  imputation  success
96        PHARYNGITIS        Mean      1.0
97   PHARYNGITIS_0.25        Mean      1.0
98    PHARYNGITIS_0.5        Mean      1.0
99   PHARYNGITIS_0.75        Mean      1.0
100       PHARYNGITIS        MICE      1.0
101  PHARYNGITIS_0.25        MICE      1.0
102   PHARYNGITIS_0.5        MICE      1.0
103  PHARYNGITIS_0.75        MICE      1.0
104       PHARYNGITIS  MissForest      1.0
105  PHARYNGITIS_0.25  MissForest      1.0
106   PHARYNGITIS_0.5  MissForest      1.0
107  PHARYNGITIS_0.75  MissForest      1.0
108       PHARYNGITIS       MIWAE      1.0
109  PHARYNGITIS_0.25       MIWAE      1.0
110   PHARYNGITIS_0.5       MIWAE      1.0
111  PHARYNGITIS_0.75       MIWAE      1.0